# Generated by Django 5.0.6 on 2024-06-28 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0001_initial'),
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.conta'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
